In [1]:
import numpy as np
import pandas as pd
import re

In [3]:
df = pd.read_csv("UNCC_sampled_new.csv")

In [4]:
df

,Date,Mobile Device Type,cchannel (eVar19) (evar19),qformuid (evar1),TreeAuthID (evar50),Visit Number,Product Reporting,Visitor_ID,csource (eVar20) (evar20),GeoSegmentation States,...,FCS Qform Optin Completed (ev373) (event373),FCS Client Signup Completed (ev73) (event73),Lender Not Matched (ev522) (event522),FormSubmit in Express Offers (ev58) (event58),Lenders Matched (ev501) (event501),Page Views,Credit Card Apply Clicked (ev69) (event69),MyLT Session Started (ev189) (event189),Express No Offers (ev13) (event13),Express Visited (ev290) (event290)
0,"January 1, 2018",Gaming Console,content,NaN,NaN,1,NaN,7732198244151778867_4134450918576237336,outbrain,texas (united states),...,0,0,0,0,0,1,0,0,0,0
1,"January 1, 2018",Gaming Console,display,11633f92-360a-448f-b416-755ea16b6419,NaN,4,Refinance,2431284746265101166_8567539867164911934,google_display_network,virginia (united states),...,0,0,0,0,0,1,0,0,0,0
2,"January 1, 2018",Gaming Console,display,3786b340-e685-4798-8004-6ee5807934c3,NaN,2,Refinance,5951927093440429627_8402229250223050888,google_display_network,florida (united states),...,0,0,0,0,0,1,0,0,0,0
3,"January 1, 2018",Gaming Console,display,3eb4e8c0-dd45-4001-820f-0a83980472d8,NaN,1,Refinance,9095128932057308643_5744753714959771864,cnn_com,ohio (united states),...,0,0,0,0,0,0,0,0,0,0
4,"January 1, 2018",Gaming Console,display,50aad01f-07a3-45ec-a575-65d89900168f,NaN,1,Refinance,7144494725347131737_7936627049048254284,google_display_network,california (united states),...,0,0,0,0,0,1,0,0,0,0
5,"January 1, 2018",Gaming Console,display,6e1c1405-ffe0-486e-9bbd-46b62efa71e0,NaN,1,NaN,3840395548288420783_2563166581193760536,criteo,oregon (united states),...,0,0,0,0,0,1,0,0,0,0
6,"January 1, 2018",Gaming Console,display,b2b0ad9e-1a0d-4153-88c1-db3564acf2be,NaN,5,Refinance,5951927093440429627_8402229250223050888,google_display_network,florida (united states),...,0,0,0,0,0,1,0,0,0,0
7,"January 1, 2018",Media Player,content,72650659-e1b0-4a0c-9bc0-da2152f4f0a3,NaN,1,Refinance,9193455551599519817_2133625214278931623,taboola,maine (united states),...,0,0,0,0,0,13,0,0,0,0
8,"January 1, 2018",Media Player,display,29f06188-b6ad-415f-9565-42d9e66f7c9a,NaN,3,Refinance,4427865552475720477_747171176657803548,google_display_network,california (united states),...,0,0,0,0,0,1,0,0,0,0
9,"January 1, 2018",Media Player,display,5f1df36c-fbd2-4e53-aaa9-ad02563a19b1,NaN,1,Refinance,1114696381134181432_6527712537278417460,google_display_network,new hampshire (united states),...,0,0,0,0,0,1,0,0,0,0
10,"January 1, 2018",Media Player,display,cff11909-1619-420f-80ce-bdfb8579141f,NaN,1,Refinance,9117345142982298598_3577160519644552955,google_display_network,pennsylvania (united states),...,0,0,0,0,0,1,0,0,0,0
11,"January 1, 2018",Media Player,sem,NaN,NaN,1,NaN,3489213251580014308_7398156064548572149,google,connecticut (united states),...,0,0,0,0,0,1,0,0,0,0
12,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1045083400990673712_8865219555642043783,NaN,wisconsin (united states),...,0,0,0,0,0,0,0,0,0,0
13,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,104959404389931813_7664988777389669386,NaN,illinois (united states),...,0,0,0,0,0,0,0,0,0,0
14,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1187440273274509770_6264289359886443009,NaN,north carolina (united states),...,0,0,0,0,0,1,0,0,0,0
15,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1259023831_2274431552,NaN,kansas (united states),...,0,0,0,0,0,0,0,0,0,0
16,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1422243278321408217_1794656872289764929,NaN,california (united states),...,0,0,0,0,0,5,0,0,0,0
17,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1470397279149965160_4056554722587805186,NaN,florida (united states),...,0,0,0,0,0,0,0,0,0,0
18,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1529432820598411557_4243204992246694562,NaN,pennsylvania (united states),...,0,0,0,0,0,1,0,0,0,0
19,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1709893692233310714_6128893313841640312,NaN,california (united states),...,0,0,0,0,0,0,0,0,0,0
20,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1745541608653249458_7227558626993931477,NaN,connecticut (united states),...,0,0,0,0,0,0,0,0,0,0
21,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1861684549292256734_6435018148321770551,NaN,illinois (united states),...,0,0,0,0,0,0,0,0,0,0
22,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2169372723960481604_258221103072382442,NaN,ohio (united states),...,0,0,0,0,0,0,0,0,0,0
23,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2176559230035865039_6028598558958540714,NaN,florida (united states),...,0,0,0,0,0,1,0,0,0,0
24,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2187762442256815536_577073384131518846,NaN,illinois (united states),...,0,0,0,0,0,2,0,0,0,0
25,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2208096828633599876_2524339848122002493,NaN,tennessee (united states),...,0,0,0,0,0,1,0,0,0,0
26,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2385508582254797716_2877051979529532200,NaN,hawaii (united states),...,0,0,0,0,0,2,0,0,0,0
27,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2390655788272990649_62550287593796688,NaN,texas (united states),...,0,0,0,0,0,1,0,0,0,0
28,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,265569730221593432_960506058289255664,NaN,florida (united states),...,0,0,0,0,0,1,0,0,0,0
29,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2666065567448156575_1758368723776643525,NaN,texas (united states),...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999970,"March 31, 2018",Tablet,social,825c3698-10b7-4220-961b-1533c18cdcf2,NaN,1,Home Equity,3051979247278651597_1747618519581597787,facebook,NaN,...,0,0,0,0,0,0,0,0,0,0
2999971,"March 31, 2018",Tablet,social,8679ce4b-858d-4f44-879e-8aa74500f62c,NaN,1,Refinance,2738442238085665918_990351591870728288,facebook,michigan (united states),...,0,0,0,0,0,1,0,0,0,0
2999972,"March 31, 2018",Tablet,social,8f479841-a226-4268-bfb9-29379c3d0dac,NaN,2,Refinance,1646352285053351098_6409211271956440438,facebook,florida (united states),...,0,0,0,0,0,2,0,0,0,0
2999973,"March 31, 2018",Tablet,social,92bf958d-144d-4c8d-9660-7ee5ecf57b09,NaN,1,Refinance,5114480043169172160_7365765535012175437,facebook,iowa (united states),...,0,0,0,0,0,3,0,0,0,0
2999974,"March 31, 2018",Tablet,social,948cbac7-5b7d-464b-9596-15f394cfaaf7,NaN,1,Refinance,3246095022172648006_8077228896379968432,facebook,florida (united states),...,0,0,0,0,0,15,0,0,0,0
2999975,"March 31, 2018",Tablet,social,98fc3609-be3f-423b-9fe7-b42afa9495e1,E0D9EBFF-C584-4310-AE32-819858602882,1,Refinance,3240927275185045235_5530436119790542375,facebook,wisconsin (united states),...,0,0,0,0,0,0,0,1,0,0
2999976,"March 31, 2018",Tablet,social,ac3956aa-7489-47ab-9692-82a850080dc0,NaN,4,Home Equity,5304079996295371104_7011336579965780622,facebook,nevada (united states),...,0,0,0,0,0,12,0,0,0,0
2999977,"March 31, 2018",Tablet,social,ad1b4f66-d1af-459b-9ddd-6cdf6226466b,NaN,1,Refinance,8483525528106927794_2673086322689744123,facebook,alabama (united states),...,0,0,0,0,0,10,0,0,0,0
2999978,"March 31, 2018",Tablet,social,b25b1269-ec20-4802-b44e-6fb52045fafe,NaN,1,Reverse Mortgage,9043133843423443410_8204087265487757541,facebook,indiana (united states),...,0,0,0,0,0,0,0,0,0,0
2999979,"March 31, 2018",Tablet,social,b683aec3-52ef-4368-85eb-c546ff6843b9,NaN,2,Home Equity,9109085113933575167_8450540456129197116,facebook,washington (united states),...,0,0,0,0,0,14,0,0,0,0
2999980,"March 31, 2018",Tablet,social,cb88317e-2fb6-4a2d-a465-a540311cc9fc,NaN,6,Refinance,8327752951312178669_4350632102071809266,facebook,ohio (united states),...,0,0,0,0,0,2,0,0,0,0
2999981,"March 31, 2018",Tablet,social,cfe78332-bc51-469f-8dec-2d387f2febe4,NaN,1,Reverse Mortgage,6521518076249051288_170989669137599378,facebook,maryland (united states),...,0,0,0,0,0,2,0,0,0,0
2999982,"March 31, 2018",Tablet,social,d62f3e2a-761e-4a6e-9a16-1364824f8ca5,NaN,1,Refinance,4796933794897345781_9074123827845285920,facebook,california (united states),...,0,0,0,0,0,1,0,0,0,0
2999983,"March 31, 2018",Tablet,social,dbcfeb41-34b2-4a74-85c7-4fba66d2ac95,NaN,1,Home Equity,7451410055334752245_3976694653819187675,facebook,arizona (united states),...,0,0,0,0,0,2,0,0,0,0
2999984,"March 31, 2018",Tablet,social,dd151baa-f8cb-4ee1-a1dc-01198791726c,NaN,1,Refinance,4913048079387628918_1089507600208746906,facebook,wisconsin (united states),...,0,0,0,0,0,2,0,0,0,0
2999985,"March 31, 2018",Tablet,social,e1984109-bd55-4cfe-af64-8cf6eb95d67a,NaN,2,Reverse Mortgage,8474581500137750173_5136818749239876599,facebook,georgia (united states),...,0,0,0,0,0,2,0,0,0,0
2999986,"March 31, 2018",Tablet,social,ea44c6ad-7fe2-439e-8265-059c61172790,NaN,6,Personal,7720872791210408324_8879797385298154805,facebook,iowa (united states),...,0,0,0,1,0,19,0,0,0,1
2999987,"March 31, 2018",Tablet,social,ecd83ebb-7c5d-46ab-8e57-9dbe0ebcb61d,NaN,1,Refinance,5994743140573466289_8324263188458442866,facebook,massachusetts (united states),...,0,0,0,0,0,14,0,0,0,0
2999988,"March 31, 2018",Tablet,social,ee4c9abf-a8cd-481b-8cc8-27ed387b5315,NaN,1,Personal,9188550043008780488_4850355055447701044,facebook,texas (united states),...,0,0,0,1,0,17,0,0,0,1
2999989,"March 31, 2018",Tablet,social,efa1e089-2835-4334-ab56-4de70bc5b4c3,NaN,1,Personal,5323512665458820856_7775738120685041918,facebook,NaN,...,0,0,0,0,0,0,0,0,0,0
2999990,"March 31, 2018",Tablet,social,f10a11ee-02a8-4611-ba84-b50be2205c53,NaN,1,Refinance,766898386836426486_333606159780703640,facebook,south carolina (united states),...,0,0,0,0,0,13,0,0,0,0
2999991,"March 31, 2018",Tablet,social,f1d8820f-c71b-45fd-843a-57432955713d,NaN,1,Refinance,1357136127484184611_7795052461046766783,facebook,maine (united states),...,0,0,0,0,0,0,0,0,0,0
2999992,"March 31, 2018",Tablet,social,f3780742-27e5-4d24-b7cf-b54453cedf98,NaN,7,Home Equity,3528547527917538180_9193024247769513026,facebook,minnesota (united states),...,0,0,0,0,0,2,0,0,0,0
2999993,"March 31, 2018",Tablet,social,f4851b2e-896c-4f7c-a3ae-37d8bddae1ac,NaN,1,Home Equity,3264145751606072124_6180621495646959649,facebook,north carolina (united states),...,0,0,0,0,0,17,0,0,0,0
2999994,"March 31, 2018",Tablet,social,f5a143ba-7459-422b-90de-7903ecbf3ff6,NaN,1,Refinance,2003904564397611122_2333946102998197800,facebook,pennsylvania (united states),...,0,0,0,0,0,16,0,0,0,0
2999995,"March 31, 2018",Tablet,social,f5f9edd5-863a-4a52-82f2-64358a78ff4f,NaN,1,Refinance,7810249774068803828_1451769962635146022,facebook,texas (united states),...,0,0,0,0,0,14,0,0,0,0
2999996,"March 31, 2018",Tablet,social,f7e3823c-2448-44ca-ac9d-e04f0cfab570,NaN,1,Refinance,8762888264550505899_5640656065562841355,facebook,new york (united states),...,0,0,0,0,0,2,0,0,0,0
2999997,"March 31, 2018",Tablet,social,fa657e24-015f-4428-ba7f-5f01827d49aa,NaN,1,Refinance,7261415900882717536_9011511284836752937,facebook,north carolina (united states),...,0,0,0,0,0,4,0,0,0,0
2999998,"March 31, 2018",Tablet,social,ffe49eea-db4c-451b-bb32-552eba91a301,NaN,2,Refinance,1424466302144561995_4869641668604106504,facebook,hawaii (united states),...,0,0,0,0,0,4,0,0,0,0
2999999,"March 31, 2018",Television,social,e54f9fa2-30f5-49d6-9831-a541a6068681,NaN,2,Reverse Mortgage,7372713496116095101_5854958976938423674,facebook,illinois (united states),...,0,0,0,0,0,6,0,0,0,0

In [51]:
df.isnull()

,Date,Mobile Device Type,cchannel (eVar19) (evar19),qformuid (evar1),TreeAuthID (evar50),Visit Number,Product Reporting,Visitor_ID,csource (eVar20) (evar20),GeoSegmentation States,...,FCS Qform Optin Completed (ev373) (event373),FCS Client Signup Completed (ev73) (event73),Lender Not Matched (ev522) (event522),FormSubmit in Express Offers (ev58) (event58),Lenders Matched (ev501) (event501),Page Views,Credit Card Apply Clicked (ev69) (event69),MyLT Session Started (ev189) (event189),Express No Offers (ev13) (event13),Express Visited (ev290) (event290)
0,False,False,False,True,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,True,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,True,True,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048545,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1048546,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048547,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048548,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048549,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048550,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048551,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048552,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048553,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048554,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048555,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048556,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048557,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048558,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048559,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048560,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048561,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048562,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048563,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048564,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048565,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048566,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048567,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1048568,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048569,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048570,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048571,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048572,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1048573,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1048574,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
np.any(df['Mobile Device Type'].isnull())

False

In [6]:
foo = df['GeoSegmentation States']

In [7]:
foo

0                   texas (united states)
1                virginia (united states)
2                 florida (united states)
3                    ohio (united states)
4              california (united states)
5                  oregon (united states)
6                 florida (united states)
7                   maine (united states)
8              california (united states)
9           new hampshire (united states)
10           pennsylvania (united states)
11            connecticut (united states)
12              wisconsin (united states)
13               illinois (united states)
14         north carolina (united states)
15                 kansas (united states)
16             california (united states)
17                florida (united states)
18           pennsylvania (united states)
19             california (united states)
20            connecticut (united states)
21               illinois (united states)
22                   ohio (united states)
23                florida (united states)
24               illinois (united states)
25              tennessee (united states)
26                 hawaii (united states)
27                  texas (united states)
28                florida (united states)
29                  texas (united states)
                        ...
2999970                               NaN
2999971          michigan (united states)
2999972           florida (united states)
2999973              iowa (united states)
2999974           florida (united states)
2999975         wisconsin (united states)
2999976            nevada (united states)
2999977           alabama (united states)
2999978           indiana (united states)
2999979        washington (united states)
2999980              ohio (united states)
2999981          maryland (united states)
2999982        california (united states)
2999983           arizona (united states)
2999984         wisconsin (united states)
2999985           georgia (united states)
2999986              iowa (united states)
2999987     massachusetts (united states)
2999988             texas (united states)
2999989                               NaN
2999990    south carolina (united states)
2999991             maine (united states)
2999992         minnesota (united states)
2999993    north carolina (united states)
2999994      pennsylvania (united states)
2999995             texas (united states)
2999996          new york (united states)
2999997    north carolina (united states)
2999998            hawaii (united states)
2999999          illinois (united states)
Name: GeoSegmentation States, Length: 3000000, dtype: object

In [61]:
foo.str.extract('\(([a-zA-Z]+\s[a-z]+|[a-zA-Z]+)')

C:\Users\shubh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """Entry point for launching an IPython kernel.

0          united states
1          united states
2          united states
3          united states
4          united states
5          united states
6          united states
7          united states
8          united states
9          united states
10         united states
11         united states
12         united states
13         united states
14         united states
15         united states
16         united states
17         united states
18         united states
19         united states
20         united states
21         united states
22         united states
23         united states
24         united states
25         united states
26         united states
27         united states
28         united states
29         united states
               ...
1048545              NaN
1048546    united states
1048547    united states
1048548    united states
1048549    united states
1048550    united states
1048551    united states
1048552    united states
1048553    united states
1048554    united states
1048555    united states
1048556    united states
1048557    united states
1048558    united states
1048559    united states
1048560    united states
1048561    united states
1048562    united states
1048563    united states
1048564    united states
1048565    united states
1048566    united states
1048567              NaN
1048568    united states
1048569    united states
1048570    united states
1048571    united states
1048572              NaN
1048573    united states
1048574    united states
Name: GeoSegmentation States, Length: 1048575, dtype: object

In [8]:
foo1 = df['GeoSegmentation States'].isnull()

In [9]:
foo1

0          False
1          False
2          False
3          False
4          False
5          False
6          False
7          False
8          False
9          False
10         False
11         False
12         False
13         False
14         False
15         False
16         False
17         False
18         False
19         False
20         False
21         False
22         False
23         False
24         False
25         False
26         False
27         False
28         False
29         False
           ...
2999970     True
2999971    False
2999972    False
2999973    False
2999974    False
2999975    False
2999976    False
2999977    False
2999978    False
2999979    False
2999980    False
2999981    False
2999982    False
2999983    False
2999984    False
2999985    False
2999986    False
2999987    False
2999988    False
2999989     True
2999990    False
2999991    False
2999992    False
2999993    False
2999994    False
2999995    False
2999996    False
2999997    False
2999998    False
2999999    False
Name: GeoSegmentation States, Length: 3000000, dtype: bool

In [10]:
len(df)

3000000

In [11]:
len(foo1)

3000000

In [15]:
df.drop(['cchannel  (eVar19) (evar19)', 'Lender Not Matched (ev522) (event522)', 'Lenders Matched (ev501) (event501)', 'Express No Offers (ev13) (event13)'], axis=1)

,Date,Mobile Device Type,qformuid (evar1),TreeAuthID (evar50),Visit Number,Product Reporting,Visitor_ID,csource (eVar20) (evar20),GeoSegmentation States,FormStart (ev57) (event57),Form Engagement 1 (ev11) (event11),Form Engagement 2 (ev12) (event12),Form Conversion (ev59) (event59),FCS Qform Optin Completed (ev373) (event373),FCS Client Signup Completed (ev73) (event73),FormSubmit in Express Offers (ev58) (event58),Page Views,Credit Card Apply Clicked (ev69) (event69),MyLT Session Started (ev189) (event189),Express Visited (ev290) (event290)
0,"January 1, 2018",Gaming Console,NaN,NaN,1,NaN,7732198244151778867_4134450918576237336,outbrain,texas (united states),0,0,0,0,0,0,0,1,0,0,0
1,"January 1, 2018",Gaming Console,11633f92-360a-448f-b416-755ea16b6419,NaN,4,Refinance,2431284746265101166_8567539867164911934,google_display_network,virginia (united states),1,0,0,0,0,0,0,1,0,0,0
2,"January 1, 2018",Gaming Console,3786b340-e685-4798-8004-6ee5807934c3,NaN,2,Refinance,5951927093440429627_8402229250223050888,google_display_network,florida (united states),1,0,0,0,0,0,0,1,0,0,0
3,"January 1, 2018",Gaming Console,3eb4e8c0-dd45-4001-820f-0a83980472d8,NaN,1,Refinance,9095128932057308643_5744753714959771864,cnn_com,ohio (united states),1,0,0,0,0,0,0,0,0,0,0
4,"January 1, 2018",Gaming Console,50aad01f-07a3-45ec-a575-65d89900168f,NaN,1,Refinance,7144494725347131737_7936627049048254284,google_display_network,california (united states),1,0,0,0,0,0,0,1,0,0,0
5,"January 1, 2018",Gaming Console,6e1c1405-ffe0-486e-9bbd-46b62efa71e0,NaN,1,NaN,3840395548288420783_2563166581193760536,criteo,oregon (united states),0,0,0,0,0,0,0,1,0,0,0
6,"January 1, 2018",Gaming Console,b2b0ad9e-1a0d-4153-88c1-db3564acf2be,NaN,5,Refinance,5951927093440429627_8402229250223050888,google_display_network,florida (united states),1,0,0,0,0,0,0,1,0,0,0
7,"January 1, 2018",Media Player,72650659-e1b0-4a0c-9bc0-da2152f4f0a3,NaN,1,Refinance,9193455551599519817_2133625214278931623,taboola,maine (united states),1,1,1,0,0,0,0,13,0,0,0
8,"January 1, 2018",Media Player,29f06188-b6ad-415f-9565-42d9e66f7c9a,NaN,3,Refinance,4427865552475720477_747171176657803548,google_display_network,california (united states),1,0,0,0,0,0,0,1,0,0,0
9,"January 1, 2018",Media Player,5f1df36c-fbd2-4e53-aaa9-ad02563a19b1,NaN,1,Refinance,1114696381134181432_6527712537278417460,google_display_network,new hampshire (united states),1,0,0,0,0,0,0,1,0,0,0
10,"January 1, 2018",Media Player,cff11909-1619-420f-80ce-bdfb8579141f,NaN,1,Refinance,9117345142982298598_3577160519644552955,google_display_network,pennsylvania (united states),1,0,0,0,0,0,0,1,0,0,0
11,"January 1, 2018",Media Player,NaN,NaN,1,NaN,3489213251580014308_7398156064548572149,google,connecticut (united states),0,0,0,0,0,0,0,1,0,0,0
12,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,1045083400990673712_8865219555642043783,NaN,wisconsin (united states),0,0,0,0,0,0,0,0,0,0,0
13,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,104959404389931813_7664988777389669386,NaN,illinois (united states),0,0,0,0,0,0,0,0,0,0,0
14,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,1187440273274509770_6264289359886443009,NaN,north carolina (united states),0,0,0,0,0,0,0,1,0,0,0
15,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,1259023831_2274431552,NaN,kansas (united states),0,0,0,0,0,0,0,0,0,0,0
16,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,1422243278321408217_1794656872289764929,NaN,california (united states),0,0,0,0,0,0,0,5,0,0,0
17,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,1470397279149965160_4056554722587805186,NaN,florida (united states),0,0,0,0,0,0,0,0,0,0,0
18,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,1529432820598411557_4243204992246694562,NaN,pennsylvania (united states),0,0,0,0,0,0,0,1,0,0,0
19,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,1709893692233310714_6128893313841640312,NaN,california (united states),0,0,0,0,0,0,0,0,0,0,0
20,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,1745541608653249458_7227558626993931477,NaN,connecticut (united states),0,0,0,0,0,0,0,0,0,0,0
21,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,1861684549292256734_6435018148321770551,NaN,illinois (united states),0,0,0,0,0,0,0,0,0,0,0
22,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,2169372723960481604_258221103072382442,NaN,ohio (united states),0,0,0,0,0,0,0,0,0,0,0
23,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,2176559230035865039_6028598558958540714,NaN,florida (united states),0,0,0,0,0,0,0,1,0,0,0
24,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,2187762442256815536_577073384131518846,NaN,illinois (united states),0,0,0,0,0,0,0,2,0,0,0
25,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,2208096828633599876_2524339848122002493,NaN,tennessee (united states),0,0,0,0,0,0,0,1,0,0,0
26,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,2385508582254797716_2877051979529532200,NaN,hawaii (united states),0,0,0,0,0,0,0,2,0,0,0
27,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,2390655788272990649_62550287593796688,NaN,texas (united states),0,0,0,0,0,0,0,1,0,0,0
28,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,265569730221593432_960506058289255664,NaN,florida (united states),0,0,0,0,0,0,0,1,0,0,0
29,"January 1, 2018",Mobile Phone,NaN,NaN,1,NaN,2666065567448156575_1758368723776643525,NaN,texas (united states),0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999970,"March 31, 2018",Tablet,825c3698-10b7-4220-961b-1533c18cdcf2,NaN,1,Home Equity,3051979247278651597_1747618519581597787,facebook,NaN,0,0,0,0,0,0,0,0,0,0,0
2999971,"March 31, 2018",Tablet,8679ce4b-858d-4f44-879e-8aa74500f62c,NaN,1,Refinance,2738442238085665918_990351591870728288,facebook,michigan (united states),1,0,0,0,0,0,0,1,0,0,0
2999972,"March 31, 2018",Tablet,8f479841-a226-4268-bfb9-29379c3d0dac,NaN,2,Refinance,1646352285053351098_6409211271956440438,facebook,florida (united states),1,0,0,0,0,0,0,2,0,0,0
2999973,"March 31, 2018",Tablet,92bf958d-144d-4c8d-9660-7ee5ecf57b09,NaN,1,Refinance,5114480043169172160_7365765535012175437,facebook,iowa (united states),1,0,0,0,0,0,0,3,0,0,0
2999974,"March 31, 2018",Tablet,948cbac7-5b7d-464b-9596-15f394cfaaf7,NaN,1,Refinance,3246095022172648006_8077228896379968432,facebook,florida (united states),1,1,1,0,0,0,0,15,0,0,0
2999975,"March 31, 2018",Tablet,98fc3609-be3f-423b-9fe7-b42afa9495e1,E0D9EBFF-C584-4310-AE32-819858602882,1,Refinance,3240927275185045235_5530436119790542375,facebook,wisconsin (united states),0,0,0,0,0,0,0,0,0,1,0
2999976,"March 31, 2018",Tablet,ac3956aa-7489-47ab-9692-82a850080dc0,NaN,4,Home Equity,5304079996295371104_7011336579965780622,facebook,nevada (united states),1,1,1,0,0,0,0,12,0,0,0
2999977,"March 31, 2018",Tablet,ad1b4f66-d1af-459b-9ddd-6cdf6226466b,NaN,1,Refinance,8483525528106927794_2673086322689744123,facebook,alabama (united states),1,1,1,0,0,0,0,10,0,0,0
2999978,"March 31, 2018",Tablet,b25b1269-ec20-4802-b44e-6fb52045fafe,NaN,1,Reverse Mortgage,9043133843423443410_8204087265487757541,facebook,indiana (united states),0,1,0,0,0,0,0,0,0,0,0
2999979,"March 31, 2018",Tablet,b683aec3-52ef-4368-85eb-c546ff6843b9,NaN,2,Home Equity,9109085113933575167_8450540456129197116,facebook,washington (united states),1,1,1,0,0,0,0,14,0,0,0
2999980,"March 31, 2018",Tablet,cb88317e-2fb6-4a2d-a465-a540311cc9fc,NaN,6,Refinance,8327752951312178669_4350632102071809266,facebook,ohio (united states),1,0,0,0,0,0,0,2,0,0,0
2999981,"March 31, 2018",Tablet,cfe78332-bc51-469f-8dec-2d387f2febe4,NaN,1,Reverse Mortgage,6521518076249051288_170989669137599378,facebook,maryland (united states),1,0,0,0,0,0,0,2,0,0,0
2999982,"March 31, 2018",Tablet,d62f3e2a-761e-4a6e-9a16-1364824f8ca5,NaN,1,Refinance,4796933794897345781_9074123827845285920,facebook,california (united states),1,0,0,0,0,0,0,1,0,0,0
2999983,"March 31, 2018",Tablet,dbcfeb41-34b2-4a74-85c7-4fba66d2ac95,NaN,1,Home Equity,7451410055334752245_3976694653819187675,facebook,arizona (united states),1,0,0,0,0,0,0,2,0,0,0
2999984,"March 31, 2018",Tablet,dd151baa-f8cb-4ee1-a1dc-01198791726c,NaN,1,Refinance,4913048079387628918_1089507600208746906,facebook,wisconsin (united states),1,1,1,0,0,0,0,2,0,0,0
2999985,"March 31, 2018",Tablet,e1984109-bd55-4cfe-af64-8cf6eb95d67a,NaN,2,Reverse Mortgage,8474581500137750173_5136818749239876599,facebook,georgia (united states),1,0,0,0,0,0,0,2,0,0,0
2999986,"March 31, 2018",Tablet,ea44c6ad-7fe2-439e-8265-059c61172790,NaN,6,Personal,7720872791210408324_8879797385298154805,facebook,iowa (united states),1,1,1,1,0,0,1,19,0,0,1
2999987,"March 31, 2018",Tablet,ecd83ebb-7c5d-46ab-8e57-9dbe0ebcb61d,NaN,1,Refinance,5994743140573466289_8324263188458442866,facebook,massachusetts (united states),1,1,1,0,0,0,0,14,0,0,0
2999988,"March 31, 2018",Tablet,ee4c9abf-a8cd-481b-8cc8-27ed387b5315,NaN,1,Personal,9188550043008780488_4850355055447701044,facebook,texas (united states),1,1,1,1,0,0,1,17,0,0,1
2999989,"March 31, 2018",Tablet,efa1e089-2835-4334-ab56-4de70bc5b4c3,NaN,1,Personal,5323512665458820856_7775738120685041918,facebook,NaN,0,0,0,0,0,0,0,0,0,0,0
2999990,"March 31, 2018",Tablet,f10a11ee-02a8-4611-ba84-b50be2205c53,NaN,1,Refinance,766898386836426486_333606159780703640,facebook,south carolina (united states),1,1,1,0,0,0,0,13,0,0,0
2999991,"March 31, 2018",Tablet,f1d8820f-c71b-45fd-843a-57432955713d,NaN,1,Refinance,1357136127484184611_7795052461046766783,facebook,maine (united states),1,0,0,0,0,0,0,0,0,0,0
2999992,"March 31, 2018",Tablet,f3780742-27e5-4d24-b7cf-b54453cedf98,NaN,7,Home Equity,3528547527917538180_9193024247769513026,facebook,minnesota (united states),1,0,0,0,0,0,0,2,0,0,0
2999993,"March 31, 2018",Tablet,f4851b2e-896c-4f7c-a3ae-37d8bddae1ac,NaN,1,Home Equity,3264145751606072124_6180621495646959649,facebook,north carolina (united states),1,1,1,0,0,0,0,17,0,0,0
2999994,"March 31, 2018",Tablet,f5a143ba-7459-422b-90de-7903ecbf3ff6,NaN,1,Refinance,2003904564397611122_2333946102998197800,facebook,pennsylvania (united states),1,1,1,0,0,0,0,16,0,0,0
2999995,"March 31, 2018",Tablet,f5f9edd5-863a-4a52-82f2-64358a78ff4f,NaN,1,Refinance,7810249774068803828_1451769962635146022,facebook,texas (united states),1,1,1,0,0,0,0,14,0,0,0
2999996,"March 31, 2018",Tablet,f7e3823c-2448-44ca-ac9d-e04f0cfab570,NaN,1,Refinance,8762888264550505899_5640656065562841355,facebook,new york (united states),1,0,0,0,0,0,0,2,0,0,0
2999997,"March 31, 2018",Tablet,fa657e24-015f-4428-ba7f-5f01827d49aa,NaN,1,Refinance,7261415900882717536_9011511284836752937,facebook,north carolina (united states),0,1,1,0,0,0,0,4,0,0,0
2999998,"March 31, 2018",Tablet,ffe49eea-db4c-451b-bb32-552eba91a301,NaN,2,Refinance,1424466302144561995_4869641668604106504,facebook,hawaii (united states),1,1,1,0,0,0,0,4,0,0,0
2999999,"March 31, 2018",Television,e54f9fa2-30f5-49d6-9831-a541a6068681,NaN,2,Reverse Mortgage,7372713496116095101_5854958976938423674,facebook,illinois (united states),1,1,1,0,0,0,0,6,0,0,0

In [16]:
df

,Date,Mobile Device Type,cchannel (eVar19) (evar19),qformuid (evar1),TreeAuthID (evar50),Visit Number,Product Reporting,Visitor_ID,csource (eVar20) (evar20),GeoSegmentation States,...,FCS Qform Optin Completed (ev373) (event373),FCS Client Signup Completed (ev73) (event73),Lender Not Matched (ev522) (event522),FormSubmit in Express Offers (ev58) (event58),Lenders Matched (ev501) (event501),Page Views,Credit Card Apply Clicked (ev69) (event69),MyLT Session Started (ev189) (event189),Express No Offers (ev13) (event13),Express Visited (ev290) (event290)
0,"January 1, 2018",Gaming Console,content,NaN,NaN,1,NaN,7732198244151778867_4134450918576237336,outbrain,texas (united states),...,0,0,0,0,0,1,0,0,0,0
1,"January 1, 2018",Gaming Console,display,11633f92-360a-448f-b416-755ea16b6419,NaN,4,Refinance,2431284746265101166_8567539867164911934,google_display_network,virginia (united states),...,0,0,0,0,0,1,0,0,0,0
2,"January 1, 2018",Gaming Console,display,3786b340-e685-4798-8004-6ee5807934c3,NaN,2,Refinance,5951927093440429627_8402229250223050888,google_display_network,florida (united states),...,0,0,0,0,0,1,0,0,0,0
3,"January 1, 2018",Gaming Console,display,3eb4e8c0-dd45-4001-820f-0a83980472d8,NaN,1,Refinance,9095128932057308643_5744753714959771864,cnn_com,ohio (united states),...,0,0,0,0,0,0,0,0,0,0
4,"January 1, 2018",Gaming Console,display,50aad01f-07a3-45ec-a575-65d89900168f,NaN,1,Refinance,7144494725347131737_7936627049048254284,google_display_network,california (united states),...,0,0,0,0,0,1,0,0,0,0
5,"January 1, 2018",Gaming Console,display,6e1c1405-ffe0-486e-9bbd-46b62efa71e0,NaN,1,NaN,3840395548288420783_2563166581193760536,criteo,oregon (united states),...,0,0,0,0,0,1,0,0,0,0
6,"January 1, 2018",Gaming Console,display,b2b0ad9e-1a0d-4153-88c1-db3564acf2be,NaN,5,Refinance,5951927093440429627_8402229250223050888,google_display_network,florida (united states),...,0,0,0,0,0,1,0,0,0,0
7,"January 1, 2018",Media Player,content,72650659-e1b0-4a0c-9bc0-da2152f4f0a3,NaN,1,Refinance,9193455551599519817_2133625214278931623,taboola,maine (united states),...,0,0,0,0,0,13,0,0,0,0
8,"January 1, 2018",Media Player,display,29f06188-b6ad-415f-9565-42d9e66f7c9a,NaN,3,Refinance,4427865552475720477_747171176657803548,google_display_network,california (united states),...,0,0,0,0,0,1,0,0,0,0
9,"January 1, 2018",Media Player,display,5f1df36c-fbd2-4e53-aaa9-ad02563a19b1,NaN,1,Refinance,1114696381134181432_6527712537278417460,google_display_network,new hampshire (united states),...,0,0,0,0,0,1,0,0,0,0
10,"January 1, 2018",Media Player,display,cff11909-1619-420f-80ce-bdfb8579141f,NaN,1,Refinance,9117345142982298598_3577160519644552955,google_display_network,pennsylvania (united states),...,0,0,0,0,0,1,0,0,0,0
11,"January 1, 2018",Media Player,sem,NaN,NaN,1,NaN,3489213251580014308_7398156064548572149,google,connecticut (united states),...,0,0,0,0,0,1,0,0,0,0
12,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1045083400990673712_8865219555642043783,NaN,wisconsin (united states),...,0,0,0,0,0,0,0,0,0,0
13,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,104959404389931813_7664988777389669386,NaN,illinois (united states),...,0,0,0,0,0,0,0,0,0,0
14,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1187440273274509770_6264289359886443009,NaN,north carolina (united states),...,0,0,0,0,0,1,0,0,0,0
15,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1259023831_2274431552,NaN,kansas (united states),...,0,0,0,0,0,0,0,0,0,0
16,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1422243278321408217_1794656872289764929,NaN,california (united states),...,0,0,0,0,0,5,0,0,0,0
17,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1470397279149965160_4056554722587805186,NaN,florida (united states),...,0,0,0,0,0,0,0,0,0,0
18,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1529432820598411557_4243204992246694562,NaN,pennsylvania (united states),...,0,0,0,0,0,1,0,0,0,0
19,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1709893692233310714_6128893313841640312,NaN,california (united states),...,0,0,0,0,0,0,0,0,0,0
20,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1745541608653249458_7227558626993931477,NaN,connecticut (united states),...,0,0,0,0,0,0,0,0,0,0
21,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,1861684549292256734_6435018148321770551,NaN,illinois (united states),...,0,0,0,0,0,0,0,0,0,0
22,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2169372723960481604_258221103072382442,NaN,ohio (united states),...,0,0,0,0,0,0,0,0,0,0
23,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2176559230035865039_6028598558958540714,NaN,florida (united states),...,0,0,0,0,0,1,0,0,0,0
24,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2187762442256815536_577073384131518846,NaN,illinois (united states),...,0,0,0,0,0,2,0,0,0,0
25,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2208096828633599876_2524339848122002493,NaN,tennessee (united states),...,0,0,0,0,0,1,0,0,0,0
26,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2385508582254797716_2877051979529532200,NaN,hawaii (united states),...,0,0,0,0,0,2,0,0,0,0
27,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2390655788272990649_62550287593796688,NaN,texas (united states),...,0,0,0,0,0,1,0,0,0,0
28,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,265569730221593432_960506058289255664,NaN,florida (united states),...,0,0,0,0,0,1,0,0,0,0
29,"January 1, 2018",Mobile Phone,NaN,NaN,NaN,1,NaN,2666065567448156575_1758368723776643525,NaN,texas (united states),...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999970,"March 31, 2018",Tablet,social,825c3698-10b7-4220-961b-1533c18cdcf2,NaN,1,Home Equity,3051979247278651597_1747618519581597787,facebook,NaN,...,0,0,0,0,0,0,0,0,0,0
2999971,"March 31, 2018",Tablet,social,8679ce4b-858d-4f44-879e-8aa74500f62c,NaN,1,Refinance,2738442238085665918_990351591870728288,facebook,michigan (united states),...,0,0,0,0,0,1,0,0,0,0
2999972,"March 31, 2018",Tablet,social,8f479841-a226-4268-bfb9-29379c3d0dac,NaN,2,Refinance,1646352285053351098_6409211271956440438,facebook,florida (united states),...,0,0,0,0,0,2,0,0,0,0
2999973,"March 31, 2018",Tablet,social,92bf958d-144d-4c8d-9660-7ee5ecf57b09,NaN,1,Refinance,5114480043169172160_7365765535012175437,facebook,iowa (united states),...,0,0,0,0,0,3,0,0,0,0
2999974,"March 31, 2018",Tablet,social,948cbac7-5b7d-464b-9596-15f394cfaaf7,NaN,1,Refinance,3246095022172648006_8077228896379968432,facebook,florida (united states),...,0,0,0,0,0,15,0,0,0,0
2999975,"March 31, 2018",Tablet,social,98fc3609-be3f-423b-9fe7-b42afa9495e1,E0D9EBFF-C584-4310-AE32-819858602882,1,Refinance,3240927275185045235_5530436119790542375,facebook,wisconsin (united states),...,0,0,0,0,0,0,0,1,0,0
2999976,"March 31, 2018",Tablet,social,ac3956aa-7489-47ab-9692-82a850080dc0,NaN,4,Home Equity,5304079996295371104_7011336579965780622,facebook,nevada (united states),...,0,0,0,0,0,12,0,0,0,0
2999977,"March 31, 2018",Tablet,social,ad1b4f66-d1af-459b-9ddd-6cdf6226466b,NaN,1,Refinance,8483525528106927794_2673086322689744123,facebook,alabama (united states),...,0,0,0,0,0,10,0,0,0,0
2999978,"March 31, 2018",Tablet,social,b25b1269-ec20-4802-b44e-6fb52045fafe,NaN,1,Reverse Mortgage,9043133843423443410_8204087265487757541,facebook,indiana (united states),...,0,0,0,0,0,0,0,0,0,0
2999979,"March 31, 2018",Tablet,social,b683aec3-52ef-4368-85eb-c546ff6843b9,NaN,2,Home Equity,9109085113933575167_8450540456129197116,facebook,washington (united states),...,0,0,0,0,0,14,0,0,0,0
2999980,"March 31, 2018",Tablet,social,cb88317e-2fb6-4a2d-a465-a540311cc9fc,NaN,6,Refinance,8327752951312178669_4350632102071809266,facebook,ohio (united states),...,0,0,0,0,0,2,0,0,0,0
2999981,"March 31, 2018",Tablet,social,cfe78332-bc51-469f-8dec-2d387f2febe4,NaN,1,Reverse Mortgage,6521518076249051288_170989669137599378,facebook,maryland (united states),...,0,0,0,0,0,2,0,0,0,0
2999982,"March 31, 2018",Tablet,social,d62f3e2a-761e-4a6e-9a16-1364824f8ca5,NaN,1,Refinance,4796933794897345781_9074123827845285920,facebook,california (united states),...,0,0,0,0,0,1,0,0,0,0
2999983,"March 31, 2018",Tablet,social,dbcfeb41-34b2-4a74-85c7-4fba66d2ac95,NaN,1,Home Equity,7451410055334752245_3976694653819187675,facebook,arizona (united states),...,0,0,0,0,0,2,0,0,0,0
2999984,"March 31, 2018",Tablet,social,dd151baa-f8cb-4ee1-a1dc-01198791726c,NaN,1,Refinance,4913048079387628918_1089507600208746906,facebook,wisconsin (united states),...,0,0,0,0,0,2,0,0,0,0
2999985,"March 31, 2018",Tablet,social,e1984109-bd55-4cfe-af64-8cf6eb95d67a,NaN,2,Reverse Mortgage,8474581500137750173_5136818749239876599,facebook,georgia (united states),...,0,0,0,0,0,2,0,0,0,0
2999986,"March 31, 2018",Tablet,social,ea44c6ad-7fe2-439e-8265-059c61172790,NaN,6,Personal,7720872791210408324_8879797385298154805,facebook,iowa (united states),...,0,0,0,1,0,19,0,0,0,1
2999987,"March 31, 2018",Tablet,social,ecd83ebb-7c5d-46ab-8e57-9dbe0ebcb61d,NaN,1,Refinance,5994743140573466289_8324263188458442866,facebook,massachusetts (united states),...,0,0,0,0,0,14,0,0,0,0
2999988,"March 31, 2018",Tablet,social,ee4c9abf-a8cd-481b-8cc8-27ed387b5315,NaN,1,Personal,9188550043008780488_4850355055447701044,facebook,texas (united states),...,0,0,0,1,0,17,0,0,0,1
2999989,"March 31, 2018",Tablet,social,efa1e089-2835-4334-ab56-4de70bc5b4c3,NaN,1,Personal,5323512665458820856_7775738120685041918,facebook,NaN,...,0,0,0,0,0,0,0,0,0,0
2999990,"March 31, 2018",Tablet,social,f10a11ee-02a8-4611-ba84-b50be2205c53,NaN,1,Refinance,766898386836426486_333606159780703640,facebook,south carolina (united states),...,0,0,0,0,0,13,0,0,0,0
2999991,"March 31, 2018",Tablet,social,f1d8820f-c71b-45fd-843a-57432955713d,NaN,1,Refinance,1357136127484184611_7795052461046766783,facebook,maine (united states),...,0,0,0,0,0,0,0,0,0,0
2999992,"March 31, 2018",Tablet,social,f3780742-27e5-4d24-b7cf-b54453cedf98,NaN,7,Home Equity,3528547527917538180_9193024247769513026,facebook,minnesota (united states),...,0,0,0,0,0,2,0,0,0,0
2999993,"March 31, 2018",Tablet,social,f4851b2e-896c-4f7c-a3ae-37d8bddae1ac,NaN,1,Home Equity,3264145751606072124_6180621495646959649,facebook,north carolina (united states),...,0,0,0,0,0,17,0,0,0,0
2999994,"March 31, 2018",Tablet,social,f5a143ba-7459-422b-90de-7903ecbf3ff6,NaN,1,Refinance,2003904564397611122_2333946102998197800,facebook,pennsylvania (united states),...,0,0,0,0,0,16,0,0,0,0
2999995,"March 31, 2018",Tablet,social,f5f9edd5-863a-4a52-82f2-64358a78ff4f,NaN,1,Refinance,7810249774068803828_1451769962635146022,facebook,texas (united states),...,0,0,0,0,0,14,0,0,0,0
2999996,"March 31, 2018",Tablet,social,f7e3823c-2448-44ca-ac9d-e04f0cfab570,NaN,1,Refinance,8762888264550505899_5640656065562841355,facebook,new york (united states),...,0,0,0,0,0,2,0,0,0,0
2999997,"March 31, 2018",Tablet,social,fa657e24-015f-4428-ba7f-5f01827d49aa,NaN,1,Refinance,7261415900882717536_9011511284836752937,facebook,north carolina (united states),...,0,0,0,0,0,4,0,0,0,0
2999998,"March 31, 2018",Tablet,social,ffe49eea-db4c-451b-bb32-552eba91a301,NaN,2,Refinance,1424466302144561995_4869641668604106504,facebook,hawaii (united states),...,0,0,0,0,0,4,0,0,0,0
2999999,"March 31, 2018",Television,social,e54f9fa2-30f5-49d6-9831-a541a6068681,NaN,2,Reverse Mortgage,7372713496116095101_5854958976938423674,facebook,illinois (united states),...,0,0,0,0,0,6,0,0,0,0

In [19]:
df_unique = df.groupby('Product Reporting').nunique()

In [20]:
df_unique

,Date,Mobile Device Type,cchannel (eVar19) (evar19),qformuid (evar1),TreeAuthID (evar50),Visit Number,Product Reporting,Visitor_ID,csource (eVar20) (evar20),GeoSegmentation States,...,FCS Qform Optin Completed (ev373) (event373),FCS Client Signup Completed (ev73) (event73),Lender Not Matched (ev522) (event522),FormSubmit in Express Offers (ev58) (event58),Lenders Matched (ev501) (event501),Page Views,Credit Card Apply Clicked (ev69) (event69),MyLT Session Started (ev189) (event189),Express No Offers (ev13) (event13),Express Visited (ev290) (event290)
Product Reporting,,,,,,,,,,,,,,,,,,,,,
Auto,90,7,20,67877,10639,164,1,67948,199,235,...,1,2,1,3,2,94,6,5,1,8
AutoPurchase,14,2,5,16,0,3,1,16,8,11,...,1,1,1,1,1,2,1,1,1,1
AutoRefinance,7,1,5,7,1,3,1,7,4,7,...,1,1,1,1,1,2,1,2,1,2
Business Loans,90,5,11,13086,653,180,1,13103,126,251,...,1,2,1,4,1,46,4,5,1,6
CreditAnalyzer,72,3,8,237,219,49,1,249,19,46,...,1,1,1,3,1,52,4,3,1,4
CreditCards,15,2,6,16,2,3,1,16,10,11,...,1,1,1,1,1,6,2,2,1,1
Debt Relief,90,5,11,4542,813,85,1,4539,60,82,...,2,1,1,3,1,36,4,4,1,5
Home Equity,90,7,15,111987,5494,203,1,110337,210,291,...,1,2,1,4,2,97,5,4,1,8
Personal,90,7,21,356358,59062,263,1,343773,381,665,...,2,2,3,5,4,126,9,7,1,13
Prequalification,74,3,7,182,23,15,1,188,19,38,...,1,1,2,2,2,25,2,2,1,3
Purchase,90,7,15,225317,15723,151,1,222043,271,441,...,2,2,5,34,6,92,9,7,1,11
Refinance,90,7,25,1180177,20109,340,1,1133478,534,1032,...,2,2,1,26,3,121,5,5,1,11
Reverse Mortgage,90,6,14,29508,675,114,1,28725,118,209,...,1,2,1,9,1,46,2,3,1,6
Student Loans,24,2,3,28,9,7,1,27,3,15,...,1,1,1,1,1,10,1,2,1,3

In [28]:
qformid = df['qformuid (evar1)']

In [29]:
treeauthid = df['TreeAuthID (evar50)']

In [30]:
treeauthid.count()

219429

In [26]:
qformid_binary = []
for val in qformid:
    if(val == val):
        qformid_binary.append(0)
    else:
        qformid_binary.append(1)

In [27]:
qformid_binary

[1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [ ]:
qformid_binary = []
for val in qform:
    if(val == val):
        qformid_binary.append(0)
    else:
        qformid_binary.append(1)

# Preprocessing starting with Credit card

In [54]:
formsignup = df['FCS Client Signup Completed (ev73) (event73)']

In [55]:
fcsqform = df['FCS Qform Optin Completed (ev373) (event373)']

In [32]:
creditcard = df['Credit Card Apply Clicked (ev69) (event69)']

In [45]:
myltsession = df['MyLT Session Started (ev189) (event189)']

In [49]:
expressvisited = df['Express Visited (ev290) (event290)']

In [66]:
myltsession_binary = []
for val in myltsession:
    if val == 0 or 1:
        myltsession_binary.append(val)
    else:
        myltsession_binary.append(0)

In [67]:
creditcard_binary = []
for val in creditcard:
    if val == 0 or 1:
        creditcard_binary.append(val)
    else:
        creditcard_binary.append(0)

In [68]:
expressvisited_binary = []
for val in expressvisited:
    if val == 0 or 1:
        expressvisited_binary.append(val)
    else:
        expressvisited_binary.append(0)

In [69]:
formsignup_binary = []
for val in formsignup:
    if val == 0 or 1:
        formsignup_binary.append(val)
    else:
        formsignup_binary.append(0)

In [70]:
fcsqform_binary = []
for val in fcsqform:
    if val == 0 or 1:
        fcsqform_binary.append(val)
    else:
        fcsqform_binary.append(0)

In [71]:
creditcard_binary

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [72]:
myltsession_binary

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [73]:
expressvisited_binary

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [74]:
formsignup_binary

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [75]:
fcsqform_binary

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]